paths:
  data: src/data
  static: public
  uploads: public/uploads
collections_config:
  data:
    path: src/data
    icon: data_usage
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
data_config:
  films:
    path: src/data/films.json
  commercials:
    path: src/data/commercials.json
  others:
    path: src/data/others.json
  writings:
    path: src/data/writings.json
timezone: Etc/UTC
