timezone: Etc/UTC

paths:
  static: public
  uploads: public/uploads

collections_config:
  short_films:
    path: src/content/short-films
    output: false
    name: Short Films
    icon: movie
    _inputs:
      vi:
        type: html
        label: "Nội dung (Tiếng Việt)"
      en:
        type: html
        label: "Content (English)"
      thumbnail:
        type: image
        label: Thumbnail

  commercials:
    path: src/content/commercials
    output: false
    name: Commercials
    icon: videocam
    _inputs:
      vi:
        type: html
        label: "Nội dung (Tiếng Việt)"
      en:
        type: html
        label: "Content (English)"
      thumbnail:
        type: image
        label: Thumbnail

  others:
    path: src/content/others
    output: false
    name: Others
    icon: folder
    _inputs:
      vi:
        type: html
        label: "Nội dung (Tiếng Việt)"
      en:
        type: html
        label: "Content (English)"
      thumbnail:
        type: image
        label: Thumbnail

  writings:
    path: src/content/writings
    output: false
    name: Writings
    icon: edit
    _inputs:
      date:
        type: text
        label: "Ngày (dd/mm/yyyy)"
      location:
        type: text
        label: "Địa điểm"
      vi:
        type: html
        label: "Nội dung (Tiếng Việt)"
      en:
        type: html
        label: "Content (English)"
